import type { Group, Topic } from "./types";

const PW_PREFIX = "Hack-The-SDGs-Python@";

/** Hex-encoded SHA-256 of the input string (Web Crypto, available on Workers). */
export async function sha256Hex(input: string): Promise<string> {
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(input));
  return Array.from(new Uint8Array(buf))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

export function personalUsername(member: string, code: string): string {
  return `${member}_${code}`;
}

export function groupUsername(group: string, code: string): string {
  return `G${group}_${code}`;
}

export function personalPassword(group: string, member: string): Promise<string> {
  return sha256Hex(`${PW_PREFIX}${group}:${member}`);
}

export function groupPassword(group: string): Promise<string> {
  return sha256Hex(`${PW_PREFIX}${group}`);
}

export interface GeneratedAccount {
  username: string;
  password: string;
}

/**
 * Expand a base username into one entry per bot. A count of 1 keeps the bare
 * name (legacy behaviour); >1 appends `_1`, `_2`, … (e.g. G1_swim_1, G1_swim_2).
 */
export function expandBots(base: string, botCount: number): string[] {
  if (botCount <= 1) return [base];
  return Array.from({ length: botCount }, (_, i) => `${base}_${i + 1}`);
}

/** Accounts a single topic implies for one group (with computed passwords). */
export async function accountsForTopicInGroup(
  group: Group,
  topic: Topic,
): Promise<GeneratedAccount[]> {
  if (topic.type === "group") {
    const password = await groupPassword(group.number);
    return expandBots(groupUsername(group.number, topic.code), topic.botCount).map((username) => ({
      username,
      password,
    }));
  }
  const accounts: GeneratedAccount[] = [];
  for (const m of group.members) {
    const password = await personalPassword(group.number, m);
    for (const username of expandBots(personalUsername(m, topic.code), topic.botCount)) {
      accounts.push({ username, password });
    }
  }
  return accounts;
}

/** All accounts a single topic implies across the given groups. */
export async function accountsForTopic(
  groups: Group[],
  topic: Topic,
): Promise<GeneratedAccount[]> {
  const accounts: GeneratedAccount[] = [];
  for (const group of groups) {
    accounts.push(...(await accountsForTopicInGroup(group, topic)));
  }
  return accounts;
}

/** All usernames a group is expected to own across the given topics (no passwords). */
export function expectedUsernamesForGroup(group: Group, topics: Topic[]): string[] {
  const names: string[] = [];
  for (const t of topics) {
    if (t.type === "group") names.push(...expandBots(groupUsername(group.number, t.code), t.botCount));
    else
      for (const m of group.members)
        names.push(...expandBots(personalUsername(m, t.code), t.botCount));
  }
  return names;
}

/** All usernames a single topic is expected to own across the given groups. */
export function expectedUsernamesForTopic(topic: Topic, groups: Group[]): string[] {
  const names: string[] = [];
  for (const g of groups) {
    if (topic.type === "group") names.push(...expandBots(groupUsername(g.number, topic.code), topic.botCount));
    else for (const m of g.members) names.push(...expandBots(personalUsername(m, topic.code), topic.botCount));
  }
  return names;
}

/** Every username generated by groups×topics — used to hide group accounts. */
export function allGeneratedUsernames(config: { groups: Group[]; topics: Topic[] }): Set<string> {
  const names = new Set<string>();
  for (const topic of config.topics) {
    for (const name of expectedUsernamesForTopic(topic, config.groups)) names.add(name);
  }
  return names;
}
